# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXZboGbuaWZzD7GVocqE6e3Q4-IbBe-5
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(0,2*np.pi,0.01)
y_sin=np.sin(x)
y_cos=np.cos(x)
y_tan = np.tan(x)

plt.style.use('ggplot')
plt.plot(x,y_sin,color='r',linewidth=1,alpha=0.6,label="sin(x)")
plt.plot(x,y_cos,color='b',linewidth=1,alpha=0.6,label='cos(x)')
plt.plot(x,y_tan,color='y',linewidth=1,alpha=0.6,label='tan(x)')
plt.legend(bbox_to_anchor=(0.2, 1), loc=1, borderaxespad=0.)
plt.ylim(ymax = 2.5)
plt.ylim(ymin = -2.5)
plt.show()